### ISSUE TITLE
npm install not working on ubuntu 16.04

### ISSUE THREAD

**Issue by SergejIsbrecht** [wzr1337/viwiServer#38]
**Description:**
Upon setting up dev-environment I got an error for
`npm install`

**Environment:**
Ubuntu 16.04 with Linux 4.8.0-51-generic
npm: 4.2.0
nodejs: v7.10.0
repo-branch: master

**Log**
> sergej@sergej-ThinkPad-L530:~/Documents/GitHub/viwiServer/src$ npm install
> speaker@0.3.0 install /home/sergej/Documents/GitHub/viwiServer/node_modules/stupid-player/node_modules/speaker
> node-gyp rebuild
> 
> make: Entering directory '/home/sergej/Documents/GitHub/viwiServer/node_modules/stupid-player/node_modules/speaker/build'
>   CC(target) Release/obj.target/output/deps/mpg123/src/output/alsa.o
> ../deps/mpg123/src/output/alsa.c:19:28: fatal error: alsa/asoundlib.h: No such file or directory
> compilation terminated.
> deps/mpg123/output.target.mk:109: recipe for target 'Release/obj.target/output/deps/mpg123/src/output/alsa.o' failed
> make: *** [Release/obj.target/output/deps/mpg123/src/output/alsa.o] Error 1
> make: Leaving directory '/home/sergej/Documents/GitHub/viwiServer/node_modules/stupid-player/node_modules/speaker/build'
> gyp ERR! build error 
> gyp ERR! stack Error: `make` failed with exit code: 2
> gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
> gyp ERR! stack     at emitTwo (events.js:106:13)
> gyp ERR! stack     at ChildProcess.emit (events.js:194:7)
> gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
> gyp ERR! System Linux 4.8.0-51-generic
> gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
> gyp ERR! cwd /home/sergej/Documents/GitHub/viwiServer/node_modules/stupid-player/node_modules/speaker
> gyp ERR! node -v v7.10.0
> gyp ERR! node-gyp -v v3.5.0
> gyp ERR! not ok 
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
> npm WARN enoent ENOENT: no such file or directory, open '/home/sergej/Documents/GitHub/viwiServer/node_modules/speaker/package.json'
> npm WARN viwiserver@0.0.4-pre1 No repository field.
> npm ERR! Linux 4.8.0-51-generic
> npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
> npm ERR! node v7.10.0
> npm ERR! npm  v4.2.0
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> 
> npm ERR! speaker@0.3.0 install: `node-gyp rebuild`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the speaker@0.3.0 install script 'node-gyp rebuild'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the speaker package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     node-gyp rebuild
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs speaker
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!     npm owner ls speaker
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     /home/sergej/.npm/_logs/2017-05-14T19_46_05_680Z-debug.log
> 

Resolution:
`sudo apt-get install libasound2-dev`

**Comment by wzr1337** [comment]
Thank you very much for filing this issue I will add docs to README.md soon..

**Comment by wzr1337** [comment]
added docs:
https://github.com/wzr1337/viwiServer/commit/6fae67371cee6fa716ec5d8cdf2fb49fc642e5fd
